name: pgvector

services:
  postgres:
    image: pgvector/pgvector:0.8.0-pg17
    container_name: pgvector-db
    environment:
      POSTGRES_DB: vectordb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "15432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: unless-stopped

  adminer:
    image: adminer
    container_name: pgvector-adminer
    restart: unless-stopped
    ports:
      - "18080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres
      ADMINER_DESIGN: "pepa-linha-dark"
    depends_on:
      - postgres

volumes:
  postgres_data:
